import type { ElementSchema } from "../engine/TemplateRenderer";

export const HERO_TEMPLATES = [
  {
    id: "hero-centered",
    name: "Centered Hero",
    description: "Big bold text, subheadline, and dual CTA buttons centered",
    getSchema: (baseId: number): ElementSchema => ({
      id: `section-hero-${baseId}`,
      type: "section",
      styles: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        alignItems: "center",
        padding: "6rem 2rem",
        background: "#ffffff",
        width: "100%",
        textAlign: "center",
        gap: "1.5rem",
      },
      children: [
        {
          id: `heading-hero-${baseId}`,
          type: "heading",
          content: "Build something amazing today.",
          styles: {
            margin: "0",
            fontSize: "3.5rem",
            fontWeight: "800",
            color: "#0f172a",
            maxWidth: "800px",
            lineHeight: "1.1",
          },
        },
        {
          id: `text-hero-${baseId}`,
          type: "text",
          content:
            "The fastest and most intuitive way to launch your next big idea. Focus on your business while we handle the design.",
          styles: {
            margin: "0",
            fontSize: "1.2rem",
            color: "#64748b",
            maxWidth: "600px",
            lineHeight: "1.5",
          },
        },
        {
          id: `container-cta-${baseId}`,
          type: "container",
          styles: {
            display: "flex",
            flexDirection: "row",
            gap: "1rem",
            alignItems: "center",
            justifyContent: "center",
            padding: "0",
            margin: "1rem 0 0 0",
            background: "transparent",
          },
          children: [
            {
              id: `button-primary-${baseId}`,
              type: "button",
              content: "Get Started Free",
              styles: {
                padding: "12px 24px",
                background: "#4f46e5",
                color: "#ffffff",
                border: "none",
                borderRadius: "8px",
                fontWeight: "600",
                fontSize: "1rem",
                cursor: "pointer",
                margin: "0",
              },
            },
            {
              id: `button-secondary-${baseId}`,
              type: "button",
              content: "View Documentation",
              styles: {
                padding: "12px 24px",
                background: "#f1f5f9",
                color: "#0f172a",
                border: "none",
                borderRadius: "8px",
                fontWeight: "600",
                fontSize: "1rem",
                cursor: "pointer",
                margin: "0",
              },
            },
          ],
        },
      ],
    }),
  },
  {
    id: "hero-split",
    name: "Split Image Hero",
    description:
      "Text and call-to-action on the left, large image on the right",
    getSchema: (baseId: number): ElementSchema => ({
      id: `section-hero-${baseId}`,
      type: "section",
      styles: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        padding: "4rem 4rem",
        background: "#ffffff",
        width: "100%",
        gap: "4rem",
      },
      children: [
        {
          id: `container-left-${baseId}`,
          type: "container",
          styles: {
            display: "flex",
            flexDirection: "column",
            gap: "1.5rem",
            flex: "1",
            alignItems: "flex-start",
            padding: "0",
            margin: "0",
            background: "transparent",
          },
          children: [
            {
              id: `heading-hero-${baseId}`,
              type: "heading",
              content: "Modern digital solutions for your brand.",
              styles: {
                margin: "0",
                fontSize: "3rem",
                fontWeight: "800",
                color: "#0f172a",
                lineHeight: "1.2",
              },
            },
            {
              id: `text-hero-${baseId}`,
              type: "text",
              content:
                "We help you build fast, beautiful, and highly scalable web applications that convert visitors into customers.",
              styles: {
                margin: "0",
                fontSize: "1.1rem",
                color: "#64748b",
                lineHeight: "1.6",
              },
            },
            {
              id: `button-primary-${baseId}`,
              type: "button",
              content: "Start Building",
              styles: {
                padding: "14px 28px",
                background: "#0f172a",
                color: "#ffffff",
                border: "none",
                borderRadius: "8px",
                fontWeight: "600",
                fontSize: "1rem",
                cursor: "pointer",
                margin: "1rem 0 0 0",
              },
            },
          ],
        },
        {
          id: `image-hero-${baseId}`,
          type: "image",
          src: "https://placehold.co/600x500/e2e8f0/64748b?text=Hero+Image",
          styles: {
            flex: "1",
            width: "100%",
            height: "auto",
            borderRadius: "16px",
            objectFit: "cover",
            boxShadow: "0 20px 25px -5px rgba(0, 0, 0, 0.1)",
          },
        },
      ],
    }),
  },
  {
    id: "hero-gradient",
    name: "Gradient Minimal",
    description: "Vibrant gradient background with white text",
    getSchema: (baseId: number): ElementSchema => ({
      id: `section-hero-${baseId}`,
      type: "section",
      styles: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        alignItems: "center",
        padding: "8rem 2rem",
        background: "linear-gradient(90deg, #4f46e5, #ec4899)",
        width: "100%",
        textAlign: "center",
        gap: "1.5rem",
      },
      children: [
        {
          id: `heading-hero-${baseId}`,
          type: "heading",
          content: "Stand out from the crowd.",
          styles: {
            margin: "0",
            fontSize: "4rem",
            fontWeight: "900",
            color: "#ffffff",
            maxWidth: "800px",
            lineHeight: "1.1",
          },
        },
        {
          id: `text-hero-${baseId}`,
          type: "text",
          content:
            "Join over 10,000 creators who are building the future with our next-generation visual editor.",
          styles: {
            margin: "0",
            fontSize: "1.25rem",
            color: "rgba(255, 255, 255, 0.9)",
            maxWidth: "600px",
            lineHeight: "1.5",
          },
        },
        {
          id: `button-primary-${baseId}`,
          type: "button",
          content: "Start Your Free Trial",
          styles: {
            padding: "14px 32px",
            background: "#ffffff",
            color: "#0f172a",
            border: "none",
            borderRadius: "50px",
            fontWeight: "700",
            fontSize: "1.1rem",
            cursor: "pointer",
            margin: "1.5rem 0 0 0",
            boxShadow: "0 10px 15px -3px rgba(0, 0, 0, 0.1)",
          },
        },
      ],
    }),
  },
];
